language: node_js

node_js:
  - 0.8

before_script:
    - sudo apt-get install apache2
    - sudo service apache2 restart
    - cd ../
    - sudo mv GMU /var/www/
    - cd /var/www/GMU

script:
    - phantomjs run.js http://localhost/GMU/test.php